<?php

namespace backend\models;

use Yii;

/**
 * This is the model class for table "user".
 *
 * @property int $id
 * @property string $username
 * @property string $auth_key
 * @property string $password_hash
 * @property string|null $password_reset_token
 * @property string $email
 * @property int $status
 * @property int $created_at
 * @property int $updated_at
 * @property string|null $verification_token
 * @property int|null $anketa_id
 * @property string $region
 * @property string $fio
 * @property int|null $tariff_id
 * @property int $contact_id
 * @property int $deal_id
 * @property string|null $stage_id
 */
class UserModel extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'user';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['username', 'auth_key', 'password_hash', 'email', 'created_at', 'updated_at', 'region', 'fio', 'deal_id'], 'required'],
            [['status', 'created_at', 'updated_at', 'anketa_id', 'tariff_id', 'deal_id', 'contact_id'], 'integer'],
            [['username', 'password_hash', 'password_reset_token', 'email', 'verification_token', 'region', 'fio', 'stage_id'], 'string', 'max' => 255],
            [['auth_key'], 'string', 'max' => 32],
            [['username'], 'unique'],
            [['email'], 'unique'],
            [['password_reset_token'], 'unique'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'username' => 'Username',
            'auth_key' => 'Auth Key',
            'password_hash' => 'Password Hash',
            'password_reset_token' => 'Password Reset Token',
            'email' => 'Email',
            'status' => 'Status',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'verification_token' => 'Verification Token',
            'anketa_id' => 'Anketa ID',
            'region' => 'Region',
            'fio' => 'Fio',
            'tariff_id' => 'Tariff ID',
            'contact_id' => 'ID контакта',
            'deal_id' => 'Deal ID',
            'stage_id' => 'Stage ID',
        ];
    }

    public function afterSave($insert, $changedAttributes)
    {
        if (!$insert){
            if (isset($changedAttributes['stage_id'])){
                $notice = Notice::findOne(['user_id' => $this->id]);
                if (!empty($notice)){
                    $params = json_decode($notice->notice_params, true);
                    if (isset($params['change'])){
                        Yii::$app->mailer->compose()
                            ->setFrom('admin@uspravozashitnik.ru')
                            ->setTo($this->email)
                            ->setSubject('Стадия сделки изменена')
                            ->setTextBody("Ваша стадия сделки изменена на {$this->stage_id}. Подробнее в личном кабинете.")
//                            ->setHtmlBody('<b>текст сообщения в формате HTML</b>')
                            ->send();
                    }
                    if (isset($params['sms'])){
                        $client = new \SoapClient('https://smsc.ru/sys/soap.php?wsdl');
                        $client->send_sms(array('login'=>'pravozashitnik', 'psw'=>'pASSusp777', 'phones'=>"+{$this->username}", 'mes'=>"Ваша стадия сделки изменена на {$this->stage_id}. Подробнее в личном кабинете.", 'sender'=>'Pravozashit'));
                    }
                }
            }
        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }
}
